kind: wasmer.io/App.v0
name: serandib-grand
owner: hirushasuhan
package: .

env:
  APP_ENV: "production"
  APP_NAME: "Serendib Grand Hotel"
  # Replace with your remote MySQL credentials (e.g. TiDB Serverless, Aiven, Railway):
  DB_HOST: "db.fr-roub1.bengt.wasmernet.com"
  DB_PORT: "20184"
  DB_NAME: "hotel_reservation_db"
  DB_USER: "user_18fa9805"
  DB_PASS: "pw_ux4WSTSYffBxu8PAbibaFnWay176299p"
  DB_SSL: "false"
  BASE_URL: "https://serandib-grand.wasmer.app"
app_id: da_K1EIZtMUYGJd
